# Generated by Django 5.2.4 on 2025-09-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalrequestuploadedfile',
            old_name='procurement_request',
            new_name='service_request',
        ),
        migrations.AddField(
            model_name='generalservicerequest',
            name='extra_detail_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
