# Generated by Django 5.2.4 on 2025-09-09 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_procurement_request_generalrequestuploadedfile_service_request_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IyeWaka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank='True', max_length=250, null='True')),
                ('detail_description', models.TextField()),
                ('url', models.CharField(max_length=250)),
                ('position', models.IntegerField(default=100)),
                ('show', models.BooleanField(default=False)),
                ('added_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['position', '-added_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, max_length=500, null=True)),
                ('youtube', models.URLField(blank=True, max_length=500, null=True)),
                ('instagram', models.URLField(blank=True, max_length=500, null=True)),
                ('tiktok', models.URLField(blank=True, max_length=500, null=True)),
                ('x', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
