# Generated by Django 5.2.4 on 2025-09-09 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_iyewaka_sociallink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procurementdeathservicerequest',
            name='parent_nin',
        ),
    ]
