# Generated by Django 5.2.4 on 2025-09-06 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_servicecategory_userapplication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalservicerequest',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='passportservicerequest',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='procurementdeathservicerequest',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='procurementservicerequest',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
