# Generated by Django 5.2.4 on 2025-09-14 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_procurementdeathservicerequest_parent_nin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalservicerequest',
            name='service_type',
        ),
        migrations.RemoveField(
            model_name='passportservicerequest',
            name='service_type',
        ),
        migrations.RemoveField(
            model_name='procurementdeathservicerequest',
            name='service_type',
        ),
        migrations.RemoveField(
            model_name='procurementservicerequest',
            name='service_type',
        ),
        migrations.AddField(
            model_name='generalservicerequest',
            name='service_options',
            field=models.ManyToManyField(to='base.servicetype'),
        ),
        migrations.AddField(
            model_name='passportservicerequest',
            name='service_options',
            field=models.ManyToManyField(to='base.servicetype'),
        ),
        migrations.AddField(
            model_name='procurementdeathservicerequest',
            name='service_options',
            field=models.ManyToManyField(to='base.servicetype'),
        ),
        migrations.AddField(
            model_name='procurementservicerequest',
            name='service_options',
            field=models.ManyToManyField(to='base.servicetype'),
        ),
    ]
