# Generated by Django 5.2.4 on 2025-09-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_generalservicerequest_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalservicerequest',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='passportservicerequest',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='procurementdeathservicerequest',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='procurementservicerequest',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='userapplication',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
