# Generated by Django 5.2.4 on 2025-09-07 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_generalservicerequest_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalservicerequest',
            name='computed_service_fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='generalservicerequest',
            name='finalized_service_fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='generalservicerequest',
            name='initial_payment_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='passportservicerequest',
            name='computed_service_fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='passportservicerequest',
            name='finalized_service_fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='passportservicerequest',
            name='initial_payment_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='passportservicerequest',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='procurementdeathservicerequest',
            name='computed_service_fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='procurementdeathservicerequest',
            name='finalized_service_fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='procurementdeathservicerequest',
            name='initial_payment_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='procurementservicerequest',
            name='computed_service_fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='procurementservicerequest',
            name='finalized_service_fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='procurementservicerequest',
            name='initial_payment_required',
            field=models.BooleanField(default=False),
        ),
    ]
