# Generated by Django 5.2.4 on 2025-09-15 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_generalservicerequest_computed_service_fee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passportservicerequest',
            name='current_residential_address',
        ),
        migrations.RemoveField(
            model_name='passportservicerequest',
            name='mother_maiden_name',
        ),
        migrations.RemoveField(
            model_name='procurementdeathservicerequest',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='procurementdeathservicerequest',
            name='lga_of_origin',
        ),
        migrations.RemoveField(
            model_name='procurementdeathservicerequest',
            name='lga_place_of_birth',
        ),
        migrations.RemoveField(
            model_name='procurementdeathservicerequest',
            name='place_of_birth',
        ),
        migrations.RemoveField(
            model_name='procurementdeathservicerequest',
            name='state_of_origin',
        ),
        migrations.RemoveField(
            model_name='procurementdeathservicerequest',
            name='village_town_origin',
        ),
        migrations.RemoveField(
            model_name='procurementservicerequest',
            name='current_residential_address',
        ),
        migrations.RemoveField(
            model_name='procurementservicerequest',
            name='mother_maiden_name',
        ),
        migrations.AddField(
            model_name='procurementservicerequest',
            name='reason_for_request',
            field=models.TextField(blank=True, null=True),
        ),
    ]
